---

- name: Install a list of packages
  apt:
    pkg:
    - chromium-browser
    - unclutter
    - lxde
  become: yes
  tags: kiosk

- name: Copy local html file
  copy:
    src: index.html
    dest: ~/
  tags: kiosk

- name: Update autostart file
  blockinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    block: |
      @xset s off
      @xset -dpms
      @xset s noblank
      @sed -i 's/"exited_cleanly": false/"exited_cleanly": true/' ~/.config/chromium-browser Default/Preferences
      @chromium-browser --noerrdialogs --kiosk file:///home/pi/index.html --incognito --disable-features=TranslateUI --check-for-update-interval=1 --simulate-critical-update
  become: yes
  tags: kiosk

- name: Unconditionally reboot the machine with all defaults
  reboot:
  become: yes
  tags: kiosk

...
