---

- name: Install a list of apt-packages (desktop)
  apt:
    pkg:
    - unclutter
    - lxde
    - xdotool
    - cec-utils
  when: host_type == "desktop"
  become: true
  tags: kiosk

- name: Install a list of apt-packages (lite)
  apt:
    install_recommends: yes
    pkg:
    - xserver-xorg
    - x11-xserver-utils
    - xinit
    - openbox
    - xdotool
    - chromium-browser
    - cec-utils
  when: host_type == "lite"
  become: true
  tags: kiosk

- name: Place out files (desktop)
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  with_items:
    - { src: 'get-serial.py', dest: '~/', mode: u+rwx }
    - { src: 'reload-script.py', dest: '~/', mode: u+rwx }
  when: host_type == "desktop"
  tags: kiosk

- name: Place out files (lite)
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  with_items:
    - { src: 'get-serial.py', dest: '~/', mode: u+rwx }
    - { src: 'reload-script.py', dest: '~/', mode: u+rwx }
    - { src: '.bash_profile', dest: '~/', mode: u+rw}
  when: host_type == "lite"
  tags: kiosk

- name: Get Device id
  command: ~/get-serial.py
  register: device_id
  tags: kiosk

- name: Set Device Id html file
  template:
    src: ../templates/show-id.html
    dest: ~/
  tags: kiosk

- name: Set local html file with iframe
  template:
    src: ../templates/index.html
    dest: ~/
  when: kiosk_iframe_url is defined
  tags: kiosk

- name: cusomize /etc/environment
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items: "{{ kiosk_env }}"
  become: true
  when: cron_check_minute is defined
  tags: kiosk

- name: Update autostart file (desktop)
  blockinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    block: |
      @xset s off
      @xset -dpms
      @xset s noblank
      @sed -i 's/"exited_cleanly": false/"exited_cleanly": true/' ~/.config/chromium/Default/Preferences
      @chromium-browser --kiosk {{ kiosk_url if (kiosk_url is defined) else 'file:///~/index.html' }} --noerrdialogs --disable-features=TranslateUI --check-for-update-interval=1 --simulate-critical-update
  when: host_type == "desktop"
  become: true
  tags: kiosk

- name: Update autostart file (lite)
  blockinfile:
    path: /etc/xdg/openbox/autostart
    block: |
      xset s off
      xset -dpms
      xset s noblank
      sed -i 's/"exited_cleanly": false/"exited_cleanly": true/' ~/.config/chromium/Default/Preferences
      chromium-browser --kiosk {{ kiosk_url if (kiosk_url is defined) else 'file:///~/index.html' }} --noerrdialogs --disable-features=TranslateUI --check-for-update-interval=1 --simulate-critical-update --noerrdialogs --disable-infobars
  when: host_type == "lite"
  become: true
  tags: kiosk

- name: add cron job for 'new experience' check
  cron:
    name: New experience cron check.
    # job: "~/reload-script.py > /dev/null 2>&1"
    job: "~/reload-script.py >> ~/cron.log"
    minute: "{{ cron_check_minute }}"
  when: cron_check_minute is defined
  tags: kiosk

- name: add cron job for 'reboot' check
  cron:
    name: New reboot cron check.
    job: "~/reload-script.py --time 60 > /dev/null 2>&1"
    special_time: "reboot"
  when: cron_check_minute is defined
  tags: kiosk

- name: Unconditionally reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    reboot_timeout: 600
  become: true
  tags: kiosk

...
