---

- name: Install a list of apt-packages
  apt:
    pkg:
    - chromium-browser
    - unclutter
    - lxde
  become: yes
  tags: kiosk

- name: Set local html file
  template:
    src: ../templates/index.html
    dest: ~/
  tags: kiosk

- name: Update autostart file
  blockinfile:
    path: /etc/xdg/lxsession/LXDE-pi/autostart
    block: |
      @xset s off
      @xset -dpms
      @xset s noblank
      @sed -i 's/"exited_cleanly": false/"exited_cleanly": true/' ~/.config/chromium/Default/Preferences
      @chromium-browser --kiosk {{ kiosk_url if (kiosk_url is defined) else 'file:///home/pi/index.html' }} --noerrdialogs --disable-features=TranslateUI --check-for-update-interval=1 --simulate-critical-update
  become: yes
  tags: kiosk

- name: Unconditionally reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    reboot_timeout: 600
  become: yes
  tags: kiosk

...
