---

- hosts: pi_kiosk
  remote_user: pi
  gather_facts: false

  tasks:
    - name: Set up authorized_keys for 'pi' user
      authorized_key: user=pi key="{{ lookup('file', item) }}"
      become: true
      with_fileglob:
        - public_keys/*_id_rsa.pub
      tags: system

  vars:
    wifi_country: "US"
    locale: "en_US.UTF-8"
    keyboard: "pc105"
    keyboard_layout: "se"
#     timezone: Etc/UTC
    locale_options:
      # Disable Default (GB) Locale
      - regexp: "^#?en_GB.UTF-8 UTF-8"
        line: "# en_GB.UTF-8 UTF-8"
      # Enable US Locale
      - regexp: "^#?en_US.UTF-8 UTF-8"
        line: "en_US.UTF-8 UTF-8"
      # Enable SE Locale
      - regexp: "^#sv_SE.UTF-8 UTF-8"
        line: "sv_SE.UTF-8 UTF-8"
    kiosk_env:
      - { 'key': 'KIOSK_AUTH_DOMAIN' , 'value': '{{ auth_domain }}' }
      - { 'key': 'KIOSK_AUTH_CLIENT_ID' , 'value': '{{ auth_client_id }}' }
      - { 'key': 'KIOSK_AUTH_CLIENT_SECRET' , 'value': '{{ auth_client_secret }}' }
      - { 'key': 'KIOSK_AUTH_API_AUDIENCE' , 'value': '{{ auth_audience }}' }
      - { 'key': 'KIOSK_AUTH_GRANT_TYPE' , 'value': '{{ auth_grant_type }}' }
      - { 'key': 'KIOSK_SERVER' , 'value': '{{ lookup_server }}' }

  roles:
    - system
    - kiosk

...
