---

- hosts: pi_kiosk
  remote_user: pi

  vars:
    wifi_country: "US"
    locale: "en_US.UTF-8"
    keyboard: "pc105"
    keyboard_layout: "se"
    timezone: Etc/UTC
    locale_options:
      # Disable Default (GB) Locale
      - regexp: "^#?en_GB.UTF-8 UTF-8"
        line: "# en_GB.UTF-8 UTF-8"
      # Enable US Locale
      - regexp: "^#?en_US.UTF-8 UTF-8"
        line: "en_US.UTF-8 UTF-8"
      # Enable SE Locale
      - regexp: "^#sv_SE.UTF-8 UTF-8"
        line: "sv_SE.UTF-8 UTF-8"

  roles:
    - system
    - kiosk

...
